import os
import json
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI

# Import the state definition and graph creation function
# Make sure your project structure allows these imports
# (e.g., run python from the root directory of Astro-Page-Agents)
from core.state import PageState
from workflow.graph import create_graph

def run_landing_page_creation():
    """Runs the full landing page creation workflow."""
    print("--- Initializing Landing Page Generation Workflow ---")
    # Load environment variables from .env file
    load_dotenv()

    # Check for necessary API key
    if not os.environ.get("OPENAI_API_KEY"):
        print("\nError: OPENAI_API_KEY not found in environment variables.")
        print("Please ensure you have a .env file in the root directory with your key:")
        print("OPENAI_API_KEY='sk-...'")
        return # Stop execution if key is missing

    # --- Configuration ---
    # Choose the LLM model. gpt-4o is good for both layout and code/image tasks.
    # You can adjust temperature for more/less creativity.
    print("Initializing LLM (gpt-4o)...")
    try:
        # Consider adding max_tokens if needed, although defaults are often fine
        llm = ChatOpenAI(model="gpt-4o", temperature=0.3)
        # Test call to ensure LLM is working (optional but good for debugging)
        # llm.invoke("Respond briefly: Hello!")
        print("LLM Initialized Successfully.")
    except Exception as e:
        print(f"\nError initializing LLM: {e}")
        print("Please check your API key, network connection, and OpenAI account status.")
        return

    # --- Get User Input ---
    print("\n--- Gathering Project Details ---")
    product_description = input("Enter product description: ")
    target_audience = input("Enter target audience: ")
    # Optional: Get image URL (leave blank if none)
    inspiration_image_url = input("Enter URL for inspiration image (optional, leave blank if none): ")

    # For simplicity now, we'll keep preferences basic or hardcoded
    preferences = {"style": "modern, clean", "tone": "professional"}
    print(f"Using default preferences: {preferences}")
    print("-----------------------------------\n")


    # --- Prepare Initial State ---
    # Create the initial state dictionary based on PageState definition
    initial_state = PageState(
        product_description=product_description,
        target_audience=target_audience,
        preferences=preferences,
        # Initialize fields that will be populated by the workflow
        layout_spec={"inspiration_image": inspiration_image_url} if inspiration_image_url else {}, # Add image URL here!
        landing_page_code=None,
        evaluation_report=None, # Not implemented in graph yet
        improved_code=None,     # Not implemented in graph yet
        suggestions=None,       # Not implemented in graph yet
        error_message=None      # Will be updated if errors occur
    )
    # Ensure layout_spec is initialized as a dict even if no image
    if 'layout_spec' not in initial_state:
        initial_state['layout_spec'] = {}


    # --- Create and Run the Graph ---
    try:
        print("Compiling workflow graph...")
        # Create the graph, passing the initialized LLM
        app = create_graph(llm)
        print("Graph compiled.")

        print("\nInvoking workflow... (This will take some time depending on model responses)")
        # Run the graph with the initial state
        # LangGraph takes care of passing state between nodes
        final_state = app.invoke(initial_state)

        print("\n--- Workflow Complete ---")

        # --- Display Results ---
        if final_state.get('error_message'):
            print(f"\n⚠️ An error occurred during the workflow: {final_state['error_message']}")

        # Display the layout specification generated by the first agent
        print("\n📋 Layout Specification:")
        # Use .get() with default value for safety
        layout_output = final_state.get('layout_spec', 'Not generated or error occurred.')
        # Pretty print if it's a dictionary
        if isinstance(layout_output, dict):
            print(json.dumps(layout_output, indent=2))
        else:
            print(layout_output)


        # Display the landing page code generated by the second agent
        print("\n💻 Generated Code (HTML):")
        # Code is stored under 'html' key in the 'landing_page_code' dict
        generated_code = final_state.get('landing_page_code', {}).get('html', None)
        if generated_code:
            print(generated_code)
            # Optional: Save the output to an HTML file for easy viewing
            try:
                output_filename = "generated_landing_page.html"
                with open(output_filename, "w", encoding="utf-8") as f:
                    f.write(generated_code)
                print(f"\n💾 Generated code saved to {output_filename}")
            except Exception as write_e:
                print(f"\nCould not save output to file: {write_e}")
        else:
            print("HTML code not generated or an error occurred.")

        # You would add printing for evaluation_report and suggestions here
        # once those agents are added to the graph.

    except Exception as e:
        print(f"\n❌ An unexpected error occurred in the main script: {e}")
        import traceback
        traceback.print_exc() # Print full traceback for debugging

if __name__ == "__main__":
    run_landing_page_creation()